services:
  - type: web
    name: utopia
    runtime: static
    buildCommand: ""
    staticPublishPath: .
    headers:
      - path: /*
        name: Cache-Control
        value: no-cache, must-revalidate
    routes:
      - type: rewrite
        source: /dashboard
        destination: /app.html
